//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Hosting.ContentSecurityPolicies.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentSecurityPolicyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentSecurityPolicyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Hosting.ContentSecurityPolicies.Resources.ContentSecurityPolicyResourc" +
                            "es", typeof(ContentSecurityPolicyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Security-Policy.
        /// </summary>
        public static string ContentSecurityPolicyHeader {
            get {
                return ResourceManager.GetString("ContentSecurityPolicyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonce-.
        /// </summary>
        public static string NonceHyphen {
            get {
                return ResourceManager.GetString("NonceHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha256-.
        /// </summary>
        public static string Sha256 {
            get {
                return ResourceManager.GetString("Sha256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha384-.
        /// </summary>
        public static string Sha384 {
            get {
                return ResourceManager.GetString("Sha384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sha512-.
        /// </summary>
        public static string Sha512 {
            get {
                return ResourceManager.GetString("Sha512", resourceCulture);
            }
        }
    }
}
