//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Hosting.ContentSecurityPolicies.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentSecuritySandboxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentSecuritySandboxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Hosting.ContentSecurityPolicies.Resources.ContentSecuritySandboxResources", typeof(ContentSecuritySandboxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-forms.
        /// </summary>
        internal static string AllowForms {
            get {
                return ResourceManager.GetString("AllowForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-modals.
        /// </summary>
        internal static string AllowModals {
            get {
                return ResourceManager.GetString("AllowModals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-orientation-lock.
        /// </summary>
        internal static string AllowOrientationLock {
            get {
                return ResourceManager.GetString("AllowOrientationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-pointer-lock.
        /// </summary>
        internal static string AllowPointerLock {
            get {
                return ResourceManager.GetString("AllowPointerLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-popups.
        /// </summary>
        internal static string AllowPopups {
            get {
                return ResourceManager.GetString("AllowPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-popups-to-escape-sandbox.
        /// </summary>
        internal static string AllowPopupsToEscapeSandbox {
            get {
                return ResourceManager.GetString("AllowPopupsToEscapeSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-presentation.
        /// </summary>
        internal static string AllowPresentation {
            get {
                return ResourceManager.GetString("AllowPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-same-origin.
        /// </summary>
        internal static string AllowSameOrigin {
            get {
                return ResourceManager.GetString("AllowSameOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-scripts.
        /// </summary>
        internal static string AllowScripts {
            get {
                return ResourceManager.GetString("AllowScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow-top-navigation.
        /// </summary>
        internal static string AllowTopNavigation {
            get {
                return ResourceManager.GetString("AllowTopNavigation", resourceCulture);
            }
        }
    }
}
