//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Hosting.ContentSecurityPolicies.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentSecuritySourceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentSecuritySourceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Hosting.ContentSecurityPolicies.Resources.ContentSecuritySourceResourc" +
                            "es", typeof(ContentSecuritySourceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdnjs.cloudflare.com.
        /// </summary>
        public static string Cloudflare {
            get {
                return ResourceManager.GetString("Cloudflare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com.
        /// </summary>
        public static string GoogleApis {
            get {
                return ResourceManager.GetString("GoogleApis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fonts.gstatic.com.
        /// </summary>
        public static string GoogleFonts {
            get {
                return ResourceManager.GetString("GoogleFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fonts.googleapis.com.
        /// </summary>
        public static string GoogleFontStyles {
            get {
                return ResourceManager.GetString("GoogleFontStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.jsdelivr.net.
        /// </summary>
        public static string JsDeliver {
            get {
                return ResourceManager.GetString("JsDeliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.microsoft.com.
        /// </summary>
        public static string MicrosoftGraph {
            get {
                return ResourceManager.GetString("MicrosoftGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.microsoftonline.com.
        /// </summary>
        public static string MicrosoftLogin {
            get {
                return ResourceManager.GetString("MicrosoftLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://stackpath.bootstrapcdn.com.
        /// </summary>
        public static string StackPathBootstrap {
            get {
                return ResourceManager.GetString("StackPathBootstrap", resourceCulture);
            }
        }
    }
}
