//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetCore.Hosting.ContentSecurityPolicies.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CspDirectiveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CspDirectiveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AspNetCore.Hosting.ContentSecurityPolicies.Resources.CspDirectiveResources", typeof(CspDirectiveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base-uri.
        /// </summary>
        public static string BaseUri {
            get {
                return ResourceManager.GetString("BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child-src.
        /// </summary>
        public static string ChildSrc {
            get {
                return ResourceManager.GetString("ChildSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect-src.
        /// </summary>
        public static string ConnectSrc {
            get {
                return ResourceManager.GetString("ConnectSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default-src.
        /// </summary>
        public static string DefaultSrc {
            get {
                return ResourceManager.GetString("DefaultSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font-src.
        /// </summary>
        public static string FontSrc {
            get {
                return ResourceManager.GetString("FontSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form-action.
        /// </summary>
        public static string FormAction {
            get {
                return ResourceManager.GetString("FormAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame-ancestors.
        /// </summary>
        public static string FrameAncestors {
            get {
                return ResourceManager.GetString("FrameAncestors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame-src.
        /// </summary>
        public static string FrameSrc {
            get {
                return ResourceManager.GetString("FrameSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to img-src.
        /// </summary>
        public static string ImgSrc {
            get {
                return ResourceManager.GetString("ImgSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest-src.
        /// </summary>
        public static string ManifestSource {
            get {
                return ResourceManager.GetString("ManifestSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media-src.
        /// </summary>
        public static string MediaSrc {
            get {
                return ResourceManager.GetString("MediaSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object-src.
        /// </summary>
        public static string ObjectSrc {
            get {
                return ResourceManager.GetString("ObjectSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sandbox.
        /// </summary>
        public static string Sandbox {
            get {
                return ResourceManager.GetString("Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script-src.
        /// </summary>
        public static string ScriptSrc {
            get {
                return ResourceManager.GetString("ScriptSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script-src-attr.
        /// </summary>
        public static string ScriptSrcAttr {
            get {
                return ResourceManager.GetString("ScriptSrcAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script-src-elem.
        /// </summary>
        public static string ScriptSrcElem {
            get {
                return ResourceManager.GetString("ScriptSrcElem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style-src.
        /// </summary>
        public static string StyleSrc {
            get {
                return ResourceManager.GetString("StyleSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style-src-attr.
        /// </summary>
        public static string StyleSrcAttr {
            get {
                return ResourceManager.GetString("StyleSrcAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style-src-elem.
        /// </summary>
        public static string StyleSrcElem {
            get {
                return ResourceManager.GetString("StyleSrcElem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade-insecure-requests.
        /// </summary>
        public static string UpgradeInsecureRequests {
            get {
                return ResourceManager.GetString("UpgradeInsecureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker-src.
        /// </summary>
        public static string WorkerSource {
            get {
                return ResourceManager.GetString("WorkerSource", resourceCulture);
            }
        }
    }
}
